name: Validations
on: [push, pull_request]

jobs:
  lint:
    name: 🧹 Code style and file formatting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10.11'

      - name: Install Python dependencies
        run: pip install poetry && poetry install

      - name: Style checks
        run: poetry run task lint

  test:
    name: 🧪 Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10.X", "3.11.X", "3.12.X"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Python dependencies
        run: pip install poetry && poetry install

      - name: Run tests
        run: poetry run task test --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
